SELECT
NUM_BO,
DESCRICAO_APRESENTACAO,
DATA_COMUNICACAO_BO,
DESCR_PERIODO,
RUBRICA,
CASE 
WHEN RUBRICA = 'Roubo (art. 157)' THEN 'Roubo'
WHEN RUBRICA = 'Furto (art. 155)' THEN 'Furto'
WHEN RUBRICA = 'Perda/Extravio' THEN 'Perda'
ELSE 'Outros' END as RUBRICA_MOD,
LOGRADOURO,
NUMERO_LOGRADOURO,
BAIRRO,
cast(CEP as text),
MARCA_OBJETO,
ANO,
MES

FROM raw_crime_data

WHERE
NOME_MUNICIPIO = 'S.PAULO'